unit codegen_x64;

{$mode objfpc}{$H+}

interface

uses
  SysUtils, Classes, ast, symtable, errors;

type
  TCodeGeneratorX64 = class
  private
    FOutput: TStringList;
    FSymTable: TSymTable;
    FFileName: String;
    FLabelCounter: Integer;

    function GenerateLabel(const Prefix: String): String;
    procedure Emit(const Instruction: String);
    procedure EmitLabel(const LabelName: String);
    
    procedure GenerateFunction(FuncNode: TFunctionNode);
    procedure GenerateStatement(StmtNode: TStatementNode);
  public
    constructor Create(ASymTable: TSymTable; const AFileName: String);
    destructor Destroy; override;

    procedure GenerateProgram(ProgramNode: TProgramNode; const OutASMPath: String);
  end;

implementation

constructor TCodeGeneratorX64.Create(ASymTable: TSymTable; const AFileName: String);
begin
  inherited Create;
  FOutput := TStringList.Create;
  FSymTable := ASymTable;
  FFileName := AFileName;
  FLabelCounter := 0;
end;

destructor TCodeGeneratorX64.Destroy;
begin
  FOutput.Free;
  inherited Destroy;
end;

function TCodeGeneratorX64.GenerateLabel(const Prefix: String): String;
begin
  Inc(FLabelCounter);
  Result := Format('.L_%s_%d', [Prefix, FLabelCounter]);
end;

procedure TCodeGeneratorX64.Emit(const Instruction: String);
begin
  FOutput.Add('    ' + Instruction);
end;

procedure TCodeGeneratorX64.EmitLabel(const LabelName: String);
begin
  FOutput.Add(LabelName + ':');
end;

procedure TCodeGeneratorX64.GenerateProgram(ProgramNode: TProgramNode; const OutASMPath: String);
var
  I: Integer;
begin
  if ProgramNode = nil then Exit;

  // Шапка NASM-файла
  FOutput.Add('; Generated by CoLang clc_fpc compiler (x86_64 NASM)');
  FOutput.Add('global main');
  FOutput.Add('extern colang_print_str');
  FOutput.Add('extern colang_print_int');
  FOutput.Add('extern colang_input_int');
  FOutput.Add('');
  FOutput.Add('section .text');

  // Генерация всех функций
  for I := 0 to ProgramNode.FunctionCount - 1 do
  begin
    GenerateFunction(ProgramNode.Functions[I]);
  end;

  // Сохранение итогового .asm файла
  FOutput.SaveToFile(OutASMPath);
end;

procedure TCodeGeneratorX64.GenerateFunction(FuncNode: TFunctionNode);
var
  I: Integer;
begin
  if FuncNode = nil then Exit;

  EmitLabel(FuncNode.Name);
  
  // Создание стекового фрейма (Prolog)
  Emit('push rbp');
  Emit('mov rbp, rsp');
  Emit('sub rsp, 128'); // Выделяем место под локальные переменные в стеке

  // Генерация тела функции
  for I := 0 to FuncNode.StatementCount - 1 do
  begin
    GenerateStatement(FuncNode.Statements[I]);
  end;

  // Завершение функции (Epilog)
  Emit('mov rsp, rbp');
  Emit('pop rbp');
  Emit('mov rax, 0'); // Код возврата 0 (success)
  Emit('ret');
  FOutput.Add('');
end;

procedure TCodeGeneratorX64.GenerateStatement(StmtNode: TStatementNode);
var
  Sym: PSymbol;
  StrLabel: String;
begin
  if StmtNode = nil then Exit;

  case StmtNode.NodeType of
    ntMakeVar:
      begin
        // Переменная уже зарегистрирована в таблице символов,
        // место в стеке выделено пропорционально StmtNode.VarSize.
      end;

    ntAssignment:
      begin
        Sym := FSymTable.Lookup(StmtNode.VarName);
        if Sym <> nil then
        begin
          // Пример: загрузка константы и сохранение в стек по смещению rbp
          Emit(Format('mov dword [rbp%d], %d', [Sym^.StackOffset, StmtNode.IntValue]));
        end;
      end;

    ntOPrint:
      begin
        // Вывод целого числа или строки
        if StmtNode.VarName <> '' then
        begin
          Sym := FSymTable.Lookup(StmtNode.VarName);
          if (Sym <> nil) and (Sym^.VarType = vtInt) then
          begin
            Emit(Format('mov edi, [rbp%d]', [Sym^.StackOffset]));
            Emit('call colang_print_int');
          end;
        end;
      end;

    ntITaker:
      begin
        Sym := FSymTable.Lookup(StmtNode.VarName);
        if (Sym <> nil) and (Sym^.VarType = vtInt) then
        begin
          Emit(Format('lea rdi, [rbp%d]', [Sym^.StackOffset]));
          Emit('call colang_input_int');
        end;
      end;

    ntReturn:
      begin
        Emit('mov rax, 0');
        Emit('mov rsp, rbp');
        Emit('pop rbp');
        Emit('ret');
      end;
  end;
end;

end.
