#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "codegen_x64.h"

static void emit(FILE* out, const char* code) {
    fprintf(out, "    %s\n", code);
}

static void emit_label(FILE* out, const char* label) {
    fprintf(out, "%s:\n", label);
}

static void generate_statement(FILE* out, ASTNode* stmt, SymTable* symtable) {
    if (!stmt) return;

    if (stmt->type == AST_ASSIGNMENT) {
        Symbol* sym = symtable_lookup(symtable, stmt->assign.name);
        if (sym) {
            fprintf(out, "    mov dword [rbp%d], %d\n", sym->stack_offset, stmt->assign.int_val);
        }
    } else if (stmt->type == AST_OPRINT) {
        if (stmt->io.var_name[0] != '\0') {
            Symbol* sym = symtable_lookup(symtable, stmt->io.var_name);
            if (sym && sym->var_type == VT_INT) {
                fprintf(out, "    mov edi, [rbp%d]\n", sym->stack_offset);
                emit(out, "call colang_print_int");
            }
        }
    } else if (stmt->type == AST_ITAKER) {
        Symbol* sym = symtable_lookup(symtable, stmt->io.var_name);
        if (sym && sym->var_type == VT_INT) {
            fprintf(out, "    lea rdi, [rbp%d]\n", sym->stack_offset);
            emit(out, "call colang_input_int");
        }
    } else if (stmt->type == AST_RETURN) {
        emit(out, "mov rax, 0");
        emit(out, "mov rsp, rbp");
        emit(out, "pop rbp");
        emit(out, "ret");
    }
}

static void generate_function(FILE* out, ASTNode* func, SymTable* symtable) {
    if (!func) return;

    emit_label(out, func->func.name);
    emit(out, "push rbp");
    emit(out, "mov rbp, rsp");
    emit(out, "sub rsp, 128");

    for (int i = 0; i < func->func.stmt_count; i++) {
        generate_statement(out, func->func.stmts[i], symtable);
    }

    emit(out, "mov rsp, rbp");
    emit(out, "pop rbp");
    emit(out, "mov rax, 0");
    emit(out, "ret");
    fprintf(out, "\n");
}

void codegen_x64_generate(ASTNode* program, SymTable* symtable, const char* out_asm_path) {
    if (!program) return;

    FILE* out = fopen(out_asm_path, "w");
    if (!out) {
        perror("Failed to open output assembly file");
        exit(1);
    }

    fprintf(out, "; Generated by CoLang clc_c compiler (x86_64 NASM)\n");
    fprintf(out, "global main\n");
    fprintf(out, "extern colang_print_str\n");
    fprintf(out, "extern colang_print_int\n");
    fprintf(out, "extern colang_input_int\n\n");
    fprintf(out, "section .text\n");

    for (int i = 0; i < program->program.func_count; i++) {
        generate_function(out, program->program.funcs[i], symtable);
    }

    fclose(out);
}
